# Generated by Django 2.0.6 on 2018-06-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_event_acronym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='título')),
                ('content', models.TextField(verbose_name='texto')),
                ('backside_title', models.CharField(blank=True, max_length=64, verbose_name='título do verso')),
                ('backside_content', models.TextField(blank=True, verbose_name='texto do verso')),
                ('background', models.ImageField(blank=True, help_text='\n        A imagem de fundo deverá ter 3508 pixels de largura e 2480 pixels de altura, correspondendo a uma \n        folha A4 na orientação de paisagem.\n        ', upload_to='backgrounds', verbose_name='imagem de fundo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Event', verbose_name='evento')),
            ],
        ),
    ]
