# Generated by Django 2.1 on 2018-08-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name = 'certificatehistory',
            options = {'verbose_name': 'histórico'},
        ),
        migrations.AlterField(
            model_name = 'certificate',
            name = 'hash',
            field = models.CharField(editable = False, max_length = 255, unique = True),
        ),
        migrations.AlterField(
            model_name = 'certificate',
            name = 'participant',
            field = models.ForeignKey(on_delete = django.db.models.deletion.PROTECT, related_name = 'certificates', to = 'certificates.Participant', verbose_name = 'participante'),
        ),
        migrations.AlterField(
            model_name = 'certificate',
            name = 'template',
            field = models.ForeignKey(on_delete = django.db.models.deletion.PROTECT, related_name = 'certificates', to = 'certificates.Template', verbose_name = 'modelo'),
        ),
        migrations.AlterField(
            model_name = 'certificatehistory',
            name = 'certificate',
            field = models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, related_name = 'logs', to = 'certificates.Certificate', verbose_name = 'certificado'),
        ),
        migrations.AlterField(
            model_name = 'template',
            name = 'backside_title',
            field = models.CharField(blank = True, max_length = 128, verbose_name = 'título do verso'),
        ),
        migrations.AlterField(
            model_name = 'template',
            name = 'event',
            field = models.ForeignKey(on_delete = django.db.models.deletion.PROTECT, related_name = 'templates', to = 'core.Event', verbose_name = 'evento'),
        ),
        migrations.AlterField(
            model_name = 'template',
            name = 'name',
            field = models.CharField(max_length = 128, verbose_name = 'nome'),
        ),
        migrations.AlterField(
            model_name = 'template',
            name = 'title',
            field = models.CharField(blank = True, max_length = 128, verbose_name = 'título'),
        ),
    ]
