# Generated by Django 2.0.7 on 2018-07-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='created_by',
        ),
    ]
