# Generated by Django 2.0.7 on 2018-07-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_remove_template_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='template',
            name='font',
            field=models.CharField(choices=[('arial', 'Arial'), ('times', 'Times New Roman')], default='arial', max_length=10, verbose_name='fonte'),
        ),
    ]
