# Generated by Django 2.0.7 on 2018-07-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20180704_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='content_font_size',
            field=models.IntegerField(default=12, verbose_name='tamanho da fonte do texto'),
        ),
        migrations.AddField(
            model_name='template',
            name='content_section_align',
            field=models.CharField(choices=[('left', 'Alinhar seção à esquerda'), ('center', 'Seção centralizada'), ('right', 'Alinhar seção à direita')], default='left', max_length=10, verbose_name='alinhamento da seção'),
        ),
        migrations.AddField(
            model_name='template',
            name='content_text_align',
            field=models.CharField(choices=[('left', 'Alinhar texto à esquerda'), ('center', 'Texto centralizado'), ('right', 'Alinhar texto à direita'), ('justify', 'Texto justificado')], default='left', max_length=10, verbose_name='alinhmento do texto'),
        ),
        migrations.AddField(
            model_name='template',
            name='content_text_color',
            field=models.CharField(choices=[('#000', 'Preto'), ('#FFF', 'Preto'), ('#CCC', 'Cinza claro'), ('#999', 'Cinza escuro')], default='#000', max_length=10, verbose_name='cor do texto'),
        ),
        migrations.AddField(
            model_name='template',
            name='content_title_distance',
            field=models.IntegerField(blank=True, default=0, verbose_name='distância do título ao texto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='font',
            field=models.CharField(choices=[('a', 'Arial'), ('t', 'Times New Roman')], default='t', max_length=1, verbose_name='fonte'),
        ),
        migrations.AddField(
            model_name='template',
            name='footer_section_align',
            field=models.CharField(blank=True, choices=[('left', 'Alinhar seção à esquerda'), ('center', 'Seção centralizada'), ('right', 'Alinhar seção à direita')], default='left', max_length=10, verbose_name='alinhamento da seção'),
        ),
        migrations.AddField(
            model_name='template',
            name='footer_text_align',
            field=models.CharField(choices=[('left', 'Alinhar texto à esquerda'), ('center', 'Texto centralizado'), ('right', 'Alinhar texto à direita'), ('justify', 'Texto justificado')], default='left', max_length=10, verbose_name='alinhamento do rodapé'),
        ),
        migrations.AddField(
            model_name='template',
            name='footer_text_color',
            field=models.CharField(choices=[('#000', 'Preto'), ('#FFF', 'Preto'), ('#CCC', 'Cinza claro'), ('#999', 'Cinza escuro')], default='#000', max_length=10, verbose_name='cor do rodapé'),
        ),
        migrations.AddField(
            model_name='template',
            name='footer_title_distance',
            field=models.IntegerField(blank=True, default=0, verbose_name='distância do texto ao rodapé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='title_align',
            field=models.CharField(choices=[('left', 'Alinhar texto à esquerda'), ('center', 'Texto centralizado'), ('right', 'Alinhar texto à direita'), ('justify', 'Texto justificado')], default='left', max_length=10, verbose_name='alinhamento do título'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_color',
            field=models.CharField(choices=[('#000', 'Preto'), ('#FFF', 'Preto'), ('#CCC', 'Cinza claro'), ('#999', 'Cinza escuro')], default='#000', max_length=10, verbose_name='cor do título'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_font_size',
            field=models.IntegerField(default=30, verbose_name='tamanho da fonte do título'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_section_align',
            field=models.CharField(choices=[('left', 'Alinhar seção à esquerda'), ('center', 'Seção centralizada'), ('right', 'Alinhar seção à direita')], default='left', max_length=10, verbose_name='alinhamento da seção'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_top_distance',
            field=models.IntegerField(blank=True, default=0, verbose_name='distância do topo ao título'),
            preserve_default=False,
        ),
    ]
