# Generated by Django 2.0.7 on 2018-07-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20180705_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content_title_distance',
            field=models.IntegerField(blank=True, default=0, verbose_name='distância do título ao texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='footer_title_distance',
            field=models.IntegerField(blank=True, default=0, verbose_name='distância do texto ao rodapé'),
        ),
    ]
