# Generated by Django 2.0.7 on 2018-07-14 12:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20180712_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='background',
            field=models.ImageField(blank=True, help_text='\n        É recomendado que imagem de fundo deverá ter 3508 pixels de largura e 2480 pixels de altura, \n        correspondendo a uma folha A4 na orientação de paisagem.\n        ', upload_to='backgrounds', verbose_name='imagem de fundo'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=tinymce.models.HTMLField(default='\n        Exemplo: Certificamos que NOME_PARTICIPANTE participou do evento NOME_EVENTO, realizado em DATA_EVENTO.\n        ', verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content_section_align',
            field=models.CharField(choices=[('left', 'Alinhar seção à esquerda'), ('center', 'Seção centralizada'), ('right', 'Alinhar seção à direita')], default='center', max_length=10, verbose_name='alinhamento da seção'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content_text_align',
            field=models.CharField(choices=[('left', 'Alinhar texto à esquerda'), ('center', 'Texto centralizado'), ('right', 'Alinhar texto à direita'), ('justify', 'Texto justificado')], default='justify', max_length=10, verbose_name='alinhmento do texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content_title_distance',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='distância do título ao texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='footer_section_align',
            field=models.CharField(blank=True, choices=[('left', 'Alinhar seção à esquerda'), ('center', 'Seção centralizada'), ('right', 'Alinhar seção à direita')], default='center', max_length=10, verbose_name='alinhamento da seção'),
        ),
        migrations.AlterField(
            model_name='template',
            name='footer_text_align',
            field=models.CharField(choices=[('left', 'Alinhar texto à esquerda'), ('center', 'Texto centralizado'), ('right', 'Alinhar texto à direita'), ('justify', 'Texto justificado')], default='center', max_length=10, verbose_name='alinhamento do rodapé'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_align',
            field=models.CharField(choices=[('left', 'Alinhar texto à esquerda'), ('center', 'Texto centralizado'), ('right', 'Alinhar texto à direita'), ('justify', 'Texto justificado')], default='center', max_length=10, verbose_name='alinhamento do título'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_section_align',
            field=models.CharField(choices=[('left', 'Alinhar seção à esquerda'), ('center', 'Seção centralizada'), ('right', 'Alinhar seção à direita')], default='center', max_length=10, verbose_name='alinhamento da seção'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_top_distance',
            field=models.PositiveIntegerField(blank=True, default=3, verbose_name='distância do topo ao título'),
        ),
    ]
