# Generated by Django 2.2.13 on 2020-08-28 15:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20180818_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatehistory',
            options={'ordering': ['-datetime'], 'verbose_name': 'histórico'},
        ),
        migrations.AddField(
            model_name='template',
            name='has_qrcode',
            field=models.BooleanField(default=True, verbose_name='tem qrcode?'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=tinymce.models.HTMLField(default='\n        Exemplo: Certificamos que NOME_COMPLETO participou do evento NOME_EVENTO, realizado em DATA_EVENTO.\n        ', help_text='\n        Os campos que compõem o certificado devem ser formados por duas palavras maísculas separadas pelo\n        caractere sublinhado (underline), como no texto de exemplo:\n        Certificamos que NOME_COMPLETO participou do evento NOME_EVENTO, realizado em DATA_EVENTO\n        ', verbose_name='texto'),
        ),
    ]
