# Generated by Django 2.0.7 on 2018-07-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20180705_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title_top_distance',
            field=models.IntegerField(blank=True, default=0, verbose_name='distância do topo ao título'),
        ),
    ]
