# Generated by Django 2.0.7 on 2018-07-14 13:48

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20180714_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=tinymce.models.HTMLField(default='\n        Exemplo: Certificamos que NOME_PARTICIPANTE participou do evento NOME_EVENTO, realizado em DATA_EVENTO.\n        ', help_text='\n        O arquivo importado deve estar no formato CSV, com a separação dos campos por ponto-e-vírgula (;) e ter, \n        obrigatoriamente, o campo NUMERO_CPF. Poderá também conter outros campos, desde que formados \n        por duas palavras maiúsculas separadas pelo caractere sublinhado (underline), como no texto \n        de exemplo. Evite usar o ponto-e-vírgula junto ao nome de um campo dentro do texto do certificado para evitar \n        problemas na importação de dados.\n        ', verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content_title_distance',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='distância do título ao texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='footer_title_distance',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='distância do texto ao rodapé'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_top_distance',
            field=models.PositiveIntegerField(blank=True, default=3, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='distância do topo ao título'),
        ),
    ]
