# Generated by Django 2.0.7 on 2018-07-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20180705_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content_font_size',
            field=models.PositiveIntegerField(default=12, verbose_name='tamanho da fonte do texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content_title_distance',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='distância do título ao texto'),
        ),
        migrations.AlterField(
            model_name='template',
            name='font',
            field=models.CharField(choices=[('a', 'Arial'), ('t', 'Times New Roman')], default='a', max_length=1, verbose_name='fonte'),
        ),
        migrations.AlterField(
            model_name='template',
            name='footer_title_distance',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='distância do texto ao rodapé'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_font_size',
            field=models.PositiveIntegerField(default=30, verbose_name='tamanho da fonte do título'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_top_distance',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='distância do topo ao título'),
        ),
    ]
