# Generated by Django 2.2.13 on 2020-08-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_template_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='backside_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='título do verso'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='título'),
        ),
    ]
