# Generated by Django 2.2.26 on 2022-01-10 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(editable=False, max_length=300, unique=True, verbose_name='slug')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(verbose_name='data de término')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='local de realização')),
                ('has_public_page', models.BooleanField(default=False, help_text='\n        Cria uma página pública do evento que mostra todos os certificados.\n        Recomenda-se não marcar essa opção caso o certificado possua dados sensíveis\n        como DNI.\n        ', verbose_name='Criar uma página pública')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
