# Generated by Django 2.1 on 2018-08-14 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'event',
            name = 'created_by',
            field = models.ForeignKey(on_delete = django.db.models.deletion.PROTECT, related_name = 'events', to = settings.AUTH_USER_MODEL, verbose_name = 'criado por'),
        ),
        migrations.AlterField(
            model_name = 'event',
            name = 'slug',
            field = models.SlugField(editable = False, unique = True, verbose_name = 'slug'),
        ),
    ]
