# Generated by Django 2.0.4 on 2018-06-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_enable_or_disable', 'Can change status is_active'),), 'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
