# Generated by Django 2.2.13 on 2020-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180814_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True, verbose_name='slug'),
        ),
    ]
