# Generated by Django 2.0.4 on 2018-06-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180615_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_enable_or_disable_user', 'Can change status is_active'),), 'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
