# Generated by Django 2.2.17 on 2020-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200828_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_public_page',
            field=models.BooleanField(default=False, verbose_name='Tem página pública?'),
        ),
    ]
