# Generated by Django 2.0.6 on 2018-06-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='acronym',
        ),
    ]
